version: "3"

services:
  # docker compose up app
  app:
    image: maven:3.6.3-adoptopenjdk-15
    working_dir: /app
    volumes:
      - maven-repo:/root/.m2
      - ${pwd:-.}:/app:ro
      - ${pwd:-.}/target:/app/target
    command: >
      sh -c "mvn clean package -Dmaven.clean.failOnError=false && 
      java -jar /app/target/app.jar"

volumes:
  maven-repo:
